server:
  port: 6066
spring:
  application:
    name: app
  redis:
    database: 0
    host: localhost
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  datasource:
    password: password
    username: username
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
security:
  jwt:
    secret: dumplingbao
    expiration: 604800 #7Days
#    exceptUrl: "/**"
    header: Authorization
    type: Bearer