spring:
  redis:
    database: 0
    host: host
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  datasource:
    write:
      password: password
      username: username
      jdbc-url: jdbc:mysql://ip:3306/db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
    read:
      password: password
      username: username
      jdbc-url: jdbc:mysql://ip:3306/db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
security:
  jwt:
    secret: dumplingbao
    expiration: 604800 #7Days
    #    exceptUrl: "/**"
    header: Authorization
    type: Bearer
aliyun:
  oss:  #oss存储相关配置
    appKey: accessKeyId
    appSecret: accessKeySecret
    endpoint: endpoint
    bucket: bucket
    url: url
    dir: dir

poolthread:
  corePoolSize: 3
  maxPoolSize: 6
  queueCapacity: 10
  keepAlive: 100
  threadName: custom